name: Compile and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download winlibs (GCC 14.1.0)
        run: Invoke-WebRequest -Uri https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-19.1.7-12.0.0-msvcrt-r3/winlibs-x86_64-posix-seh-gcc-14.2.0-mingw-w64msvcrt-12.0.0-r3.zip -OutFile winlibs.zip

      - name: Extract winlibs
        run: 7z x winlibs.zip -oC:\winlibs

      - name: Add winlibs to PATH
        run: echo "C:\winlibs\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Compile C++ file
        run: g++ Magisk.cpp -o magisk.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            magisk.exe
            NewblueStacksRoot.cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
